name: Harmonoid
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_android:
    name: Harmonoid Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Set Git Commit Hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check Git Commit Hash
        run: echo ${{ steps.vars.outputs.sha_short }}
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Create Key Store
        id: create_key_store
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "keystore.pfx"
          encodedString: ${{ secrets.KEY_STORE }}

      - name: Create Key Properties
        id: create_key_properties
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "key.properties"
          encodedString: ${{ secrets.KEY_PROPERTIES }}

      - run: cp "${{ steps.create_key_store.outputs.filePath }}" android/app/keystore.jks
      - run: cp "${{ steps.create_key_properties.outputs.filePath }}" android/key.properties

      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter build apk --verbose
      - run: cp build/app/outputs/flutter-apk/app-release.apk harmonoid-android.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: ""
          tag_name: "vnext"
          files: |
            harmonoid-android.apk
          token: ${{ secrets.ACCESS_TOKEN }}
